/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Bida.form;

import com.Bida.swing.Customers;
import com.Bida.swing.CustomersDAO;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class Form_Customers extends javax.swing.JPanel {

    CustomersDAO dao = new CustomersDAO();
    String strImage = null;

    /**
     * Creates new form Form_Customers
     */
    public Form_Customers() {
        initComponents();
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) dataCUSTOMER.getModel();
        model.setRowCount(0);
        for (Customers cus : dao.getAllCustomer()) {
            Object rowData[] = new Object[5];
            rowData[0] = cus.getId();
            rowData[1] = cus.getName();
            rowData[2] = cus.getPhone();
            rowData[3] = cus.isGender() ? "MALE" : "FEMALE";
            rowData[4] = cus.getImage();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataCUSTOMER = new javax.swing.JTable();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ibImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btSAVE = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Customers:");

        dataCUSTOMER.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PHONE", "TIME PLAYING", "TABLE BOOKED", "PURCHASED"
            }
        ));
        dataCUSTOMER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataCUSTOMERMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataCUSTOMER);

        txtPhone.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fullname:");

        ibImage.setBackground(new java.awt.Color(204, 255, 255));
        ibImage.setText("Image");
        ibImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ibImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ibImageMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Phone:");

        txtName.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N

        btSAVE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSAVE.setText("Search");
        btSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSAVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btSAVE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(ibImage, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSAVE))
                    .addComponent(ibImage, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void reset() {
        txtName.setText("");
        txtPhone.setText("");
        ibImage.setText("Image");
        ibImage.setIcon(null);
        strImage = null;
    }
    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void ibImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibImageMouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser jf = new JFileChooser();
            jf.showOpenDialog(null);
            File file = jf.getSelectedFile();
            Image img = ImageIO.read(file);
            strImage = file.getName();
            ibImage.setText("");
            int width = ibImage.getWidth();
            int height = ibImage.getHeight();
            ibImage.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }//GEN-LAST:event_ibImageMouseClicked

    public Customers getModel() throws ParseException {

        return null;

    }
    private void btSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSAVEActionPerformed
        String nameText = txtName.getText().toLowerCase().trim();
    String phoneText = txtPhone.getText().toLowerCase().trim();

    // Check if either name or phone number is empty
    if (nameText.isEmpty() || phoneText.isEmpty()) {
        // Display an error message dialog
        JOptionPane.showMessageDialog(this, "Please enter both Name and Phone Number!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        DefaultTableModel model = (DefaultTableModel) dataCUSTOMER.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        sorter.setRowFilter(RowFilter.regexFilter(nameText));
                sorter.setRowFilter(RowFilter.regexFilter(phoneText));

        dataCUSTOMER.setRowSorter(sorter);
    }//GEN-LAST:event_btSAVEActionPerformed

    public void setModel(Customers cus) {
//        txtID.setText(cus.getId());
//        txtName.setText(cus.getName());
//        txtPhone.setText(cus.getPhone());
//        if (cus.isGender()) {
//            gdMale.isSelected();
//        } else {
//            gdFemale.isSelected();
//        }
//        // load hinh anh;
//        ibImage.setText("");
//        ImageIcon imgIcon = new ImageIcon(getClass().getResource("com/Bida/icon/" + cus.getImage()));
//        Image img = imgIcon.getImage();
//        img.getScaledInstance(ibImage.getWidth(), ibImage.getY(), 0);
    }
    private void dataCUSTOMERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataCUSTOMERMouseClicked
        // TODO add your handling code here:
        int id = dataCUSTOMER.rowAtPoint(evt.getPoint());
        String cusid = dataCUSTOMER.getValueAt(id, 0).toString();
        Customers cus = dao.getCusById(cusid);
    }//GEN-LAST:event_dataCUSTOMERMouseClicked

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        try (FileReader reader = new FileReader("khachhang.txt")) {
            BufferedReader br = new BufferedReader(reader);
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");

                String name = data[0];
                String phone = data[1];
                String time = data[2];
                String table = data[3];
                String total = data[4];

                DefaultTableModel model = (DefaultTableModel) dataCUSTOMER.getModel();
                model.addRow(new Object[]{name, phone, time, table, total});
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading data from file!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formAncestorAdded
    private int findNextAvailableID(List<String[]> data) {
        int maxID = 0;
        Set<Integer> usedIDs = new HashSet<>();

        for (String[] record : data) {
            if (record.length > 0) {
                try {
                    int currentID = Integer.parseInt(record[0]);
                    maxID = Math.max(maxID, currentID);
                    usedIDs.add(currentID);
                } catch (NumberFormatException e) {
                }
            }
        }
        for (int i = maxID + 1;; i++) {
            if (!usedIDs.contains(i)) {
                return i;
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSAVE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dataCUSTOMER;
    private javax.swing.JLabel ibImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
